### ISSUE TITLE
Creating a new post should include layout

### ISSUE THREAD

**Issue by mihneadb** [mgax/jekyllcms#5]
Usually, jekyll uses `layout: post` for posts. It should be included when creating a new post.

**Comment by mgax** [comment]
You can [set a default](http://jekyllrb.com/docs/configuration/#front-matter-defaults) layout. The "new site" template (which is used when JekyllCMS detects an empty repository, or a missing `gh-pages` branch) does set [a default](https://github.com/mgax/jekyllcms/blob/master/src/initial.jsx#L12-L15).
